### ISSUE TITLE
支持bigsur吗？

### ISSUE THREAD

**Issue by kiraraty** [lxyoucan/Hases-z7-kp7sc-OC#1]

**Comment by lxyoucan** [comment]
理论上是支持big sur的因为opencore几乎是最新版本的了。但是本人没有实测安装big sur,因为需要用到一些big sur暂不支持的软件。

**Comment by kiraraty** [comment]
感谢，我试试看

**Comment by kiraraty** [comment]
更新后，进度条直接快跑满，然后黑屏，无法进入系统

**Comment by kiraraty** [comment]
已更换efi安装时bigsur成功了 http://bbs.pcbeta.com/viewthread-1879510-1-1.html
相似模具的

**Comment by lxyoucan** [comment]
非常感谢你的测试与分享。 @kiraraty
